# Application
spring.application.name=hospital-system

# PostgreSQL Database (Render)
spring.datasource.url=jdbc:postgresql://dpg-d6oqo81aae7s73firtmg-a:5432/hosp_mbrs
spring.datasource.username=hosp_mbrs_user
spring.datasource.password=UjTnRAFDhT8HaynCSrEQl5comaheZ9S9
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server port (important for Render)
server.port=${PORT:8080}

# JWT
app.jwt.secret=HospitalAppointmentSecretKey2026VerySecureSecretKey
app.jwt.expiration=86400000
